services:
  discovery-service:
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  api-gateway-service:
    environment:
      - EUREKA_URL=http://discovery-service:8761/eureka
      - AUTHORIZATION_SERVICE_URL=http://authorization-service:8081
      - PROFILE_SERVICE_URL=http://profile-service:8082
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
    depends_on:
      discovery-service:
        condition: service_healthy
  authorization-service:
    environment:
      - EUREKA_URL=http://discovery-service:8761/eureka
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - AUTHORIZATION_PROFILE_RABBITMQ_HOST=${AUTHORIZATION_PROFILE_RABBITMQ_HOST:-authorization-profile-rabbitmq}
      - AUTHORIZATION_PROFILE_RABBITMQ_PORT=${AUTHORIZATION_PROFILE_RABBITMQ_PORT:-5672}
      - AUTHORIZATION_PROFILE_RABBITMQ_USERNAME=${AUTHORIZATION_PROFILE_RABBITMQ_USERNAME:-local_app}
      - AUTHORIZATION_PROFILE_RABBITMQ_PASSWORD=${AUTHORIZATION_PROFILE_RABBITMQ_PASSWORD:-password}
      - AUTHORIZATION_PROFILE_RABBITMQ_VIRTUAL_HOST=${AUTHORIZATION_PROFILE_RABBITMQ_VIRTUAL_HOST:-/}
      - MAILGUN_URL=${MAILGUN_URL:-http://localhost:8079}
      - MAILGUN_USERNAME=${MAILGUN_USERNAME:-api}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-token}
    depends_on:
      discovery-service:
        condition: service_healthy
      authorization-profile-rabbitmq:
        condition: service_healthy
  profile-service:
    environment:
      - EUREKA_URL=http://discovery-service:8761/eureka
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - PROFILE_IMAGES_ACCESS_KEY=${PROFILE_IMAGES_ACCESS_KEY:-local_app}
      - PROFILE_IMAGES_ACCESS_SECRET=${PROFILE_IMAGES_ACCESS_SECRET:-secret}
      - AUTHORIZATION_PROFILE_RABBITMQ_HOST=${AUTHORIZATION_PROFILE_RABBITMQ_HOST:-authorization-profile-rabbitmq}
      - AUTHORIZATION_PROFILE_RABBITMQ_PORT=${AUTHORIZATION_PROFILE_RABBITMQ_PORT:-5672}
      - AUTHORIZATION_PROFILE_RABBITMQ_USERNAME=${AUTHORIZATION_PROFILE_RABBITMQ_USERNAME:-local_app}
      - AUTHORIZATION_PROFILE_RABBITMQ_PASSWORD=${AUTHORIZATION_PROFILE_RABBITMQ_PASSWORD:-password}
      - AUTHORIZATION_PROFILE_RABBITMQ_VIRTUAL_HOST=${AUTHORIZATION_PROFILE_RABBITMQ_VIRTUAL_HOST:-/}
    depends_on:
      discovery-service:
        condition: service_healthy
      authorization-profile-rabbitmq:
        condition: service_healthy
  task-service:
    environment:
      - EUREKA_URL=http://discovery-service:8761/eureka
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
    depends_on:
      discovery-service:
        condition: service_healthy