import { api } from '../apiSlice.ts';

const PASSWORD_RESET_API = '/password/reset';

/**
 * Represents an API object for user-related operations. This API is generated by `api.injectEndpoints`
 * and includes various endpoints to interact with user functionalities, such as initiating password reset requests.
 *
 * @constant {object} usersApi
 * @property {function} requestPasswordReset A mutation endpoint to request a password reset for a user.
 *                                           Takes an email address as input and triggers a POST request
 *                                           to the password reset API with the provided email.
 */
export const usersApi = api.injectEndpoints({
  endpoints: (builder) => ({
    requestPasswordReset: builder.mutation<undefined, string>({
      query: (email) => ({
        url: PASSWORD_RESET_API + `?email=${email}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
      }),
    }),
  }),
});

export const { useRequestPasswordResetMutation } = usersApi;
