spring.data.mongodb.uri = mongodb+srv://${MONGO_USER}:${MONGO_USER_PASSWORD}@maxq-cluster.8dkbus1\.mongodb\.net/?retryWrites=true&w=majority
spring.data.mongodb.database = work-manager
spring.data.mongodb.auto-index-creation = true