name: API Gateway Service Deploy
on:
  workflow_run:
    workflows:
      - UI Tests Pipeline
    types:
      - completed
    secrets: inherit
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  api-gateway-changes:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
    outputs:
      api-gateway: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in API Gateway
        uses: ./.github/actions/check-changes
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'backend/api-gateway-service/**'

  api-gateway-service-deploy:
    needs: api-gateway-changes
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push' &&
      needs.api-gateway-changes.outputs.api-gateway == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: ./.github/actions/download-artifact
        with:
          artifact_name: api-gateway-service-jar
          path: backend/api-gateway-service/build/libs
          github_token: ${{ github.token }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./backend/api-gateway-service
          file: ./backend/api-gateway-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-gateway-service:1.0.1
            ${{ secrets.DOCKER_USERNAME }}/api-gateway-service:latest
          labels: api-gateway-service

      - name: Deploy to Render
        run: |
          curl ${{ secrets.API_GATEWAY_RENDER_HOOK }}

      - name: Wait for application to be ready
        uses: './.github/actions/health-check'
        with:
          timeout_minutes: 10
          url: ${{ secrets.API_GATEWAY_API_URL }}/actuator/health