name: Authorization Service Deploy
on:
  workflow_run:
    workflows:
      - UI Tests Pipeline
    types:
      - completed
    secrets: inherit
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
    outputs:
      authorization: ${{ steps.filter.outputs.any_modified || steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in frontend
        uses: tj-actions/changed-files@v46.0.5
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'backend/authorization-service/**'

      - name: Print changed files
        run: |
          echo ${{ steps.filter.outputs.all_changed_and_modified_files }}

  authorization-service-deploy:
    needs: changes
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push' &&
      needs.changes.outputs.authorization == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: ./.github/actions/download-artifact
        with:
          artifact_name: authorization-service-jar
          path: backend/authorization-service/build/libs
          github_token: ${{ github.token }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./backend/authorization-service
          file: ./backend/authorization-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/authorization-service:1.0.0
            ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest
          labels: authorization-service

      - name: Deploy to Render
        run: |
          curl ${{ secrets.AUTHORIZATION_RENDER_HOOK }}

      - name: Wait for application to be ready
        timeout-minutes: 10
        env:
          HEALTHCHECK_URL: ${{ secrets.AUTHORIZATION_API_URL }}/actuator/health
        run: |
          ATTEMPT=1
          
          while true; do
            echo "Attempt #$ATTEMPT: Checking health endpoint at $HEALTHCHECK_URL..."
          
            RESPONSE=$(curl -s $HEALTHCHECK_URL || true)
            echo "$RESPONSE"
          
            if echo "$RESPONSE" | grep -q '"status":"UP"'; then
              echo "Service is up and healthy! Health check passed."
              exit 0
            else
              echo "Service is not available yet. Waiting 10 seconds before the next attempt..."
              sleep 10
            fi
          
            ATTEMPT=$((ATTEMPT + 1))
          done
          
          echo "Health check failed to pass within the timeout period."
          exit 1