name: Demo Service CI Pipeline

on:
  push:
    paths:
      - backend/demo/**
    branches: ["*"]
  pull_request:
    paths:
      - backend/demo/**
    branches: ["*"]
  workflow_dispatch:

jobs:
  demo-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./backend/gradlew

      - name: Install dependencies
        run: ./gradlew clean demo:build -x test -x check -x assemble -x pmdMain -x pmdTest
        working-directory: backend

      - name: Run Lint Checks
        run: ./gradlew demo:check
        working-directory: backend

      - name: Run Unit Tests
        run: ./gradlew demo:test
        working-directory: backend

      - name: Build
        run: ./gradlew demo:assemble
        working-directory: backend

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: demo-tests
          path: backend/demo/build/reports
