name: Discovery Service CI Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  discovery-changes:
    runs-on: ubuntu-latest
    outputs:
      discovery: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in Discovery Service
        uses: ./.github/actions/check-changes
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'backend/discovery-service/**'

  discovery-service:
    needs: discovery-changes
    if: needs.discovery-changes.outputs.discovery == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./backend/gradlew

      - name: Install dependencies
        run: ./gradlew clean discovery-service:build -x test -x check -x assemble -x pmdMain -x pmdTest
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Run Lint Checks
        run: ./gradlew discovery-service:check
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Run Unit Tests
        run: ./gradlew discovery-service:test
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Build
        run: ./gradlew discovery-service:assemble
        env:
          SPRING_PROFILES_ACTIVE: PROD
        working-directory: backend

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: discovery-service-tests
          path: backend/discovery-service/build/reports

      - name: Upload JAR file artifact
        uses: actions/upload-artifact@v4
        with:
          name: discovery-service-jar
          path: |
            backend/discovery-service/build/libs/discovery-service-*.jar
            !backend/discovery-service/build/libs/discovery-service-*-plain.jar
