name: Frontend CI Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  frontend-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in frontend
        uses: ./.github/actions/check-changes
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'frontend/**'

  frontend:
    needs: frontend-changes
    if: needs.frontend-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run Format
        run: npm run format
        working-directory: frontend

      - name: Run Lint (fix + check)
        run: npm run lint:fix
        working-directory: frontend

      - name: Run Tests
        run: npm run coverage
        working-directory: frontend

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
