name: Deploy frontend to Google Cloud Storage Bucket

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  ui-tests:
    uses: ./.github/workflows/ui-tests-ci.yml

  frontend-deploy:
    runs-on: ubuntu-latest

    needs:
      - ui-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: frontend
          name: frontend-build
          path: frontend/dist

      - name: Test build artifact
        run: ls -R