name: Deploy frontend to Google Cloud Storage Bucket

on:
  workflow_run:
    workflows:
      - UI Tests Pipeline
    types:
      - completed
    secrets: inherit
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main'

#  &&
      #      github.event.workflow_run.event == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ui-tests-ci.yml
          name: frontend-build
          path: frontend/dist
          github_token: '${{ github.token }}'

      - name: Test secrets
        run: echo '${{ secrets.GCP_PROJECT_ID }}'

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Upload to Cloud Storage
        run: |
          gsutil -m rsync -R ./frontend/dist gs://'${{ secrets.GCS_BUCKET }}'
          gsutil iam ch allUsers:objectViewer gs://'${{ secrets.GCS_BUCKET }}'
