name: Postman API Tests for Demo Service

on:
  workflow_call:
    secrets:
      JWT_PRIVATE_KEY:
        required: true
      MAIL_USERNAME:
        required: true
      MAIL_PASSWORD:
        required: true
      ROBOT_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      authorization: ${{ steps.filter.outputs.any_modified || steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in frontend
        uses: tj-actions/changed-files@v46.0.5
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: |
            backend/authorization-service/**
            postman-api-tests/authorization-service/**

      - name: Print changed files
        run: |
          echo ${{ steps.filter.outputs.all_changed_and_modified_files }}

  authorization-service-ci:
    uses: ./.github/workflows/authorization-service-ci.yml
    secrets:
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}git

  postman-tests-authorization-service:
    runs-on: ubuntu-latest

    needs:
      - changes
      - authorization-service-ci

    if: needs.changes.outputs.authorization == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.1'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Download Authorization Service JAR
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ui-tests-ci.yml
          name: authorization-service-jar
          path: backend/authorization-service/build/libs
          check_artifacts: true
          search_artifacts: true
          github_token: '${{ github.token }}'

      - name: Run Compose Containers
        run: docker compose up --build -d
        working-directory: backend/authorization-service
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          SPRING_PROFILES_ACTIVE: QA

      - name: Install Newman
        run: npm install -g newman

      - name: Install HTMLExtra
        run: npm install -g newman-reporter-htmlextra

      - name: Wait for application to be ready
        timeout-minutes: 2
        env:
          HEALTHCHECK_URL: http://localhost:8081/actuator/health
        run: |
          ATTEMPT=1
          
          while true; do
            echo "Attempt #$ATTEMPT: Checking health endpoint at $HEALTHCHECK_URL..."
          
            RESPONSE=$(curl -s $HEALTHCHECK_URL || true)
            echo "$RESPONSE"
          
            if echo "$RESPONSE" | grep -q '"status":"UP"'; then
              echo "Service is up and healthy! Health check passed."
              exit 0
            else
              echo "Service is not available yet. Waiting 10 seconds before the next attempt..."
              sleep 10
            fi
          
            ATTEMPT=$((ATTEMPT + 1))
          done
          
          echo "Health check failed to pass within the timeout period."
          exit 1

      - name: Run Postman Tests
        run: |
          newman run "EWM - Authorization Service.postman_collection.json" \
          --reporters='cli,htmlextra' \
          --reporter-htmlextra-export ./results/report.html \
          --global-var "robotToken=${{ secrets.ROBOT_TOKEN }}"
        working-directory: postman-api-tests/authorization-service

      - name: Upload Postman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-report-authorization-service
          path: postman-api-tests/authorization-service/results