name: Profile Service CI Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  profile-changes:
    runs-on: ubuntu-latest
    outputs:
      profile: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in Profile Service
        uses: ./.github/actions/check-changes
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'backend/profile-service/**'

  profile-service:
    needs: profile-changes
    if: needs.profile-changes.outputs.profile == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./backend/gradlew

      - name: Install dependencies
        run: ./gradlew clean profile-service:build -x test -x check -x assemble -x pmdMain -x pmdTest
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Run Lint Checks
        run: ./gradlew profile-service:check
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Run Unit Tests
        run: ./gradlew profile-service:test
        env:
          SPRING_PROFILES_ACTIVE: QA
        working-directory: backend

      - name: Build
        run: ./gradlew profile-service:assemble
        env:
          SPRING_PROFILES_ACTIVE: PROD
        working-directory: backend

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: profile-service-tests
          path: backend/profile-service/build/reports

      - name: Upload JAR file artifact
        uses: actions/upload-artifact@v4
        with:
          name: profile-service-jar
          path: |
            backend/profile-service/build/libs/profile-service-*.jar
            !backend/profile-service/build/libs/profile-service-*-plain.jar