name: Trigger application UI testing
run-name: Trigger application UI testing

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    uses: ./.github/workflows/cloud-run-deploy.yaml
    permissions:
      contents: read
      security-events: write
      actions: read
      id-token: write
    secrets:
      GCPToken: ${{ secrets.GCP_SA_KEY }}

  trigger-ui-tests:
    name: Trigger UI Tests
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Trigger Chrome UI Testing
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPOSITORY_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/QxaM/employee-and-work-order-management-ui-tests/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
