name: UI Tests Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  api-tests:
    uses: ./.github/workflows/postman-demo-service-ci.yml

  ui-tests:
    runs-on: ubuntu-latest

    needs:
      - frontend
      - api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Backend Dependencies
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
        working-directory: backend

      - name: Start Demo Service
        run: ./gradlew demo:bootRun &
        working-directory: backend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Preview Frontend
        run: npm run preview &
        working-directory: frontend

      - name: Wait for services Health Check
        run: sleep 20

      - name: Run UI Tests
        run:  |
          chmod +x ./gradlew
          ./gradlew test
        working-directory: uitests

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: uitests/build/reports
