name: UI Tests Pipeline

on:
  workflow_run:
    workflows:
      - Frontend CI Pipeline
      - Postman API Tests for Demo Service
    types:
      - completed
    conclusion: success
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Backend Dependencies
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
        working-directory: backend

      - name: Start Demo Service
        run: ./gradlew demo:bootRun &
        working-directory: backend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Preview Frontend
        run: npm run preview &
        working-directory: frontend

      - name: Wait for services Health Check
        run: sleep 20

      - name: Run UI Tests
        run: ./gradlew test
        working-directory: uitests

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-report
          path: uitests/build/reports
